# Generated by Django 5.0.3 on 2024-03-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognews',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Загрузите фото'),
        ),
        migrations.AddField(
            model_name='blognews',
            name='music',
            field=models.FileField(null=True, upload_to='music/', verbose_name='Загрузите аудио'),
        ),
        migrations.AddField(
            model_name='blognews',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='Укажите цену'),
        ),
        migrations.AddField(
            model_name='blognews',
            name='type_news',
            field=models.CharField(choices=[('Шоу бизнес', 'Шоу бизнес'), ('Авто', 'Авто'), ('Вечерний Бишкек', 'Вечерний Бишкек'), ('Технологии', 'Технологии')], max_length=100, null=True, verbose_name='Выберите тип новости'),
        ),
        migrations.AddField(
            model_name='blognews',
            name='youtube_url',
            field=models.URLField(null=True, verbose_name='Ссылка на ютуб'),
        ),
        migrations.AlterField(
            model_name='blognews',
            name='description',
            field=models.TextField(null=True, verbose_name='Напишите новость'),
        ),
        migrations.AlterField(
            model_name='blognews',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Напишите название новости'),
        ),
    ]
